language: elixir
elixir:
  - 1.8.1
  - 1.8.0
  - 1.7.4
  - 1.7.3
  - 1.7.2
  - 1.7.1
  - 1.7.0
  - 1.6.6
  - 1.6.5
otp_release:
  - 21.2
  - 21.1
  - 21.0
  - 20.3
  - 20.1
  - 20.0
sudo: false
matrix:
  include:
    - install:
      - mix local.hex --force
      - mix archive.install hex bunt '~> 0.2' --force
      - mix archive.install hex credo '~> 1.0' --force
      script:
      - mix format --check-formatted --dry-run
      - mix credo --strict
    - secure: fpg2leA+GSEcbW+B9lkUPFHAsPoiq9VIF48izB4anR65TZgPIHoy7W04Ly+cHSDuPYPxxtCuZW5YU5ZBi3GAXNLsKZG3uTaoLQj+atZsDdyZNW7Z7Df2uVm3eIK7wC7XojalNtShYx56xTC19xrH01n6VouAcbgJ3TIfxQCraDk=
      script: mix coveralls.travis
